@Catalog.API_HostAdress=http://localhost:5025
@ApiVersion = 1.0

### CRUD Tecnhology
###--------------- CREATE ---------------
POST  https://{{Catalog.API_HostAdress}}/api/technology/create
Content-Type: application/json

{
  "name": "TypeSCript",
  "version": "string",
  "description": "string"
}

###--------------- READ ---------------
// Filtro Base
POST  https://{{Catalog.API_HostAdress}}/api/technology
Content-Type: application/json

{
  "numPage": 0,
  "numRecordsPage": 0,
  "order": "string",
  "sort": "string",
  "records": 0,
  "numFilter": 0,
  "textFilter": "string",
  "stateFilter": 0,
  "startDate": "string",
  "endDate": "string",
  "download": true
}
###

// filtro 1
POST  https://{{Catalog.API_HostAdress}}/api/technology
Content-Type: application/json

{
  "numPage": 1,
  "numRecordsPage": 10,
  "order": "asc",
  "sort": "Id"
}
###
// filtro 2 // numFilter: 1 = nombre ; 2 = descripción
POST  https://{{Catalog.API_HostAdress}}/api/technology
Content-Type: application/json

{
  "numFilter": 1, 
  "textFilter": "s"
}

###--------------- UPDATE ---------------
@UpdateTechnologyId = 1
PUT  https://{{Catalog.API_HostAdress}}/api/technology/update/{{UpdateTechnologyId}}
Content-Type: application/json

{
  "name": "ACtualiz",
  "version": "string",
  "description": "string"
}

###--------------- DElETE ---------------
@DeleteTechnologyId = 4
DELETE  https://{{Catalog.API_HostAdress}}/api/technology/delete/{{DeleteTechnologyId}}

###--------------- SELECT ---------------
GET  https://{{Catalog.API_HostAdress}}/api/technology/select

###--------------- READ BY ID ---------------
GET  https://{{Catalog.API_HostAdress}}/api/technology/1

